-- Relay domain schema: docs/DATA_MODEL.md and docs/STATE_TRANSITIONS.md.
-- DATETIME values are UTC by application convention. Forward-only Flyway migration.

CREATE TABLE workflows (
  `id` VARCHAR(128) NOT NULL,
  `name` TEXT NOT NULL,
  `description` TEXT,
  `status` VARCHAR(32) NOT NULL,
  `draft_definition` JSON NOT NULL,
  `published_definition` JSON,
  `published_at` DATETIME(6),
  `revision` BIGINT NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  INDEX ix_workflows_created (created_at,id),
  CONSTRAINT ck_workflow_status CHECK (status IN ('draft','published')),
  CONSTRAINT ck_publication_pair CHECK ((published_definition IS NULL AND published_at IS NULL) OR (published_definition IS NOT NULL AND published_at IS NOT NULL)),
  CONSTRAINT ck_published_required CHECK (status<>'published' OR published_definition IS NOT NULL),
  CONSTRAINT ck_workflow_time CHECK (updated_at>=created_at AND (published_at IS NULL OR published_at>=created_at)),
  CONSTRAINT ck_workflow_revision CHECK (revision>=0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE runs (
  `run_id` VARCHAR(128) NOT NULL,
  `workflow_id` VARCHAR(128) NOT NULL,
  `definition_snapshot` JSON NOT NULL,
  `execution_policy` JSON NOT NULL,
  `input` JSON NOT NULL,
  `trigger_type` VARCHAR(32) NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `current_node_id` VARCHAR(128),
  `steps_executed` BIGINT NOT NULL,
  `next_step_sequence` BIGINT NOT NULL,
  `ai_tokens_used` BIGINT,
  `ai_usage_complete` BOOLEAN NOT NULL,
  `error` JSON,
  `cancel_requested_at` DATETIME(6),
  `cancel_requested_by` TEXT,
  `cancellation_reason` TEXT,
  `created_at` DATETIME(6) NOT NULL,
  `started_at` DATETIME(6),
  `finished_at` DATETIME(6),
  `revision` BIGINT NOT NULL,
  PRIMARY KEY (run_id),
  CONSTRAINT fk_run_workflow FOREIGN KEY (workflow_id) REFERENCES workflows (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  INDEX ix_runs_created (created_at,run_id),
  INDEX ix_runs_workflow (workflow_id,created_at,run_id),
  INDEX ix_runs_status (status,created_at,run_id),
  CONSTRAINT ck_run_status CHECK (status IN ('queued','running','waiting_approval','succeeded','failed','cancelled')),
  CONSTRAINT ck_run_trigger CHECK (trigger_type IN ('manual','webhook')),
  CONSTRAINT ck_run_sequence CHECK (next_step_sequence>=1),
  CONSTRAINT ck_run_usage_boolean CHECK (ai_usage_complete IN (0,1)),
  CONSTRAINT ck_run_terminal CHECK ((status IN ('succeeded','failed','cancelled') AND finished_at IS NOT NULL) OR (status IN ('queued','running','waiting_approval') AND finished_at IS NULL)),
  CONSTRAINT ck_run_time CHECK ((started_at IS NULL OR started_at>=created_at) AND (finished_at IS NULL OR finished_at>=created_at) AND (started_at IS NULL OR finished_at IS NULL OR finished_at>=started_at) AND (cancel_requested_at IS NULL OR cancel_requested_at>=created_at)),
  CONSTRAINT ck_run_steps_executed CHECK (steps_executed>=0),
  CONSTRAINT ck_run_ai_tokens_used CHECK (ai_tokens_used>=0),
  CONSTRAINT ck_run_revision CHECK (revision>=0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE steps (
  `run_id` VARCHAR(128) NOT NULL,
  `sequence` BIGINT NOT NULL,
  `node_id` VARCHAR(128) NOT NULL,
  `node_type` VARCHAR(32) NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `wait_reason` VARCHAR(32),
  `final_attempt` BIGINT NOT NULL,
  `resolved_input` JSON,
  `dispatch_request` JSON,
  `output` JSON,
  `error` JSON,
  `idempotency_key` VARCHAR(320),
  `selected_next_node_id` VARCHAR(128),
  `resume_at` DATETIME(6),
  `ai_repair_count` BIGINT NOT NULL,
  `ai_repair_request` JSON,
  `tokens_prompt` BIGINT,
  `tokens_completion` BIGINT,
  `ai_usage_complete` BOOLEAN NOT NULL,
  `started_at` DATETIME(6),
  `finished_at` DATETIME(6),
  `duration_ms` BIGINT,
  PRIMARY KEY (run_id,`sequence`),
  CONSTRAINT fk_step_run FOREIGN KEY (run_id) REFERENCES runs (run_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  UNIQUE KEY uq_step_idempotency (idempotency_key),
  INDEX ix_steps_node (run_id,node_id,`sequence`),
  CONSTRAINT ck_step_sequence CHECK (`sequence`>=1),
  CONSTRAINT ck_step_status CHECK (status IN ('running','waiting','succeeded','failed','cancelled')),
  CONSTRAINT ck_step_wait CHECK ((status='waiting' AND wait_reason IS NOT NULL AND wait_reason IN ('delay','retry','approval')) OR (status<>'waiting' AND wait_reason IS NULL)),
  CONSTRAINT ck_step_repair CHECK (ai_repair_count IN (0,1)),
  CONSTRAINT ck_step_repair_request CHECK ((ai_repair_count=0 AND ai_repair_request IS NULL) OR (ai_repair_count=1 AND ai_repair_request IS NOT NULL)),
  CONSTRAINT ck_step_usage_boolean CHECK (ai_usage_complete IN (0,1)),
  CONSTRAINT ck_step_terminal CHECK ((status IN ('succeeded','failed','cancelled') AND finished_at IS NOT NULL AND duration_ms IS NOT NULL) OR (status IN ('running','waiting') AND finished_at IS NULL AND duration_ms IS NULL)),
  CONSTRAINT ck_step_time CHECK (started_at IS NULL OR finished_at IS NULL OR finished_at>=started_at),
  CONSTRAINT ck_step_final_attempt CHECK (final_attempt>=0),
  CONSTRAINT ck_step_tokens_prompt CHECK (tokens_prompt>=0),
  CONSTRAINT ck_step_tokens_completion CHECK (tokens_completion>=0),
  CONSTRAINT ck_step_duration_ms CHECK (duration_ms>=0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE step_attempts (
  `run_id` VARCHAR(128) NOT NULL,
  `step_sequence` BIGINT NOT NULL,
  `attempt_no` BIGINT NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `cause` VARCHAR(32) NOT NULL,
  `claim_generation` BIGINT NOT NULL,
  `request` JSON,
  `output` JSON,
  `error` JSON,
  `provider` TEXT,
  `model` TEXT,
  `tokens_prompt` BIGINT,
  `tokens_completion` BIGINT,
  `started_at` DATETIME(6) NOT NULL,
  `finished_at` DATETIME(6),
  `duration_ms` BIGINT,
  PRIMARY KEY (run_id,step_sequence,attempt_no),
  CONSTRAINT fk_attempt_step FOREIGN KEY (run_id,step_sequence) REFERENCES steps (run_id,`sequence`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT ck_attempt_identity CHECK (step_sequence>=1 AND attempt_no>=1),
  CONSTRAINT ck_attempt_status CHECK (status IN ('running','succeeded','failed','uncertain')),
  CONSTRAINT ck_attempt_cause CHECK (cause IN ('initial','transport_retry','schema_repair','recovery')),
  CONSTRAINT ck_attempt_terminal CHECK ((status IN ('succeeded','failed') AND finished_at IS NOT NULL AND duration_ms IS NOT NULL) OR (status IN ('running','uncertain') AND finished_at IS NULL AND duration_ms IS NULL)),
  CONSTRAINT ck_attempt_time CHECK (finished_at IS NULL OR finished_at>=started_at),
  CONSTRAINT ck_attempt_claim_generation CHECK (claim_generation>=0),
  CONSTRAINT ck_attempt_tokens_prompt CHECK (tokens_prompt>=0),
  CONSTRAINT ck_attempt_tokens_completion CHECK (tokens_completion>=0),
  CONSTRAINT ck_attempt_duration_ms CHECK (duration_ms>=0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE approvals (
  `id` VARCHAR(128) NOT NULL,
  `run_id` VARCHAR(128) NOT NULL,
  `step_sequence` BIGINT NOT NULL,
  `node_id` VARCHAR(128) NOT NULL,
  `message` LONGTEXT NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `decided_by` TEXT,
  `decided_at` DATETIME(6),
  `closed_at` DATETIME(6),
  `close_reason` TEXT,
  PRIMARY KEY (id),
  UNIQUE KEY uq_approval_step (run_id,step_sequence),
  CONSTRAINT fk_approval_step FOREIGN KEY (run_id,step_sequence) REFERENCES steps (run_id,`sequence`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  INDEX ix_approvals_pending (status,closed_at,created_at,id),
  INDEX ix_approvals_gate (run_id,status,step_sequence),
  CONSTRAINT ck_approval_sequence CHECK (step_sequence>=1),
  CONSTRAINT ck_approval_status CHECK (status IN ('pending','approved','rejected','closed')),
  CONSTRAINT ck_approval_evidence CHECK ((status='pending' AND decided_by IS NULL AND decided_at IS NULL AND closed_at IS NULL AND close_reason IS NULL) OR (status IN ('approved','rejected') AND decided_by IS NOT NULL AND decided_at IS NOT NULL AND closed_at IS NULL AND close_reason IS NULL) OR (status='closed' AND decided_by IS NULL AND decided_at IS NULL AND closed_at IS NOT NULL AND close_reason IS NOT NULL)),
  CONSTRAINT ck_approval_time CHECK ((decided_at IS NULL OR decided_at>=created_at) AND (closed_at IS NULL OR closed_at>=created_at))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;

CREATE TABLE queue_jobs (
  `run_id` VARCHAR(128) NOT NULL,
  `step_sequence` BIGINT,
  `target_node_id` VARCHAR(128) NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `available_at` DATETIME(6) NOT NULL,
  `lease_owner` TEXT,
  `lease_until` DATETIME(6),
  `claim_generation` BIGINT NOT NULL,
  `retry_count` BIGINT NOT NULL,
  `next_attempt_cause` VARCHAR(32),
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (run_id),
  CONSTRAINT fk_queue_run FOREIGN KEY (run_id) REFERENCES runs (run_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  INDEX ix_queue_step (run_id,step_sequence),
  CONSTRAINT fk_queue_step FOREIGN KEY (run_id,step_sequence) REFERENCES steps (run_id,`sequence`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  INDEX ix_queue_due (status,available_at,run_id),
  INDEX ix_queue_expired (status,lease_until,run_id),
  CONSTRAINT ck_queue_sequence CHECK (step_sequence IS NULL OR step_sequence>=1),
  CONSTRAINT ck_queue_status CHECK (status IN ('ready','leased','inactive')),
  CONSTRAINT ck_queue_lease CHECK ((status='leased' AND lease_owner IS NOT NULL AND lease_until IS NOT NULL) OR (status IN ('ready','inactive') AND lease_owner IS NULL AND lease_until IS NULL)),
  CONSTRAINT ck_queue_cause CHECK (next_attempt_cause IN ('initial','transport_retry','schema_repair','recovery')),
  CONSTRAINT ck_queue_time CHECK (updated_at>=created_at),
  CONSTRAINT ck_queue_claim_generation CHECK (claim_generation>=0),
  CONSTRAINT ck_queue_retry_count CHECK (retry_count>=0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;
